[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
create_token = "4tH7DHxfoeTGGqbgdPdjCwfYf8JwvujdMmD31BD9BswV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
